# -*- coding: utf-8 -*-
"""
Civitai / A1111 / ComfyUI prompt extractor.

Images generated by Civitai, Automatic1111 or ComfyUI carry their generation
settings inside the file. Nothing is encrypted - it is plain text sitting in
places a normal image viewer never shows you:

  1. PNG text chunk 'parameters'  -> A1111/Civitai style block:
         <positive prompt>
         Negative prompt: <negative>
         Steps: 20, Sampler: DPM++ 2M, CFG scale: 5, ...
  2. PNG text chunks 'prompt' / 'workflow' -> ComfyUI JSON (API + UI graph).
  3. JPEG/WEBP EXIF UserComment (0x9286) -> same A1111 block, stored as
     b'UNICODE\\x00' followed by UTF-16 text.

Civitai ComfyUI exports additionally stash a small JSON blob under
workflow['extra']['extraMetadata'] with explicit 'prompt' / 'negativePrompt'
keys - that is the most reliable source when present.

IMPORTANT: a ComfyUI IMAGE is a decoded pixel tensor and carries NO metadata.
The prompt can only be recovered from the FILE, which is why the node here is
a loader (it reads the file itself) rather than something you plug an IMAGE
into.
"""

import json
import os
import re

# Keys that start the A1111 settings line ("Steps: 20, Sampler: ...").
_A1111_PARAM_LINE = re.compile(
    r"^(Steps|Sampler|Schedule type|CFG scale|Seed|Size|Model hash|Model|"
    r"Denoising strength|Clip skip|Version|VAE|VAE hash|Hires upscale|"
    r"Hires steps|Hires upscaler|Lora hashes|TI hashes|ADetailer model|"
    r"Civitai resources|Civitai metadata)\s*:",
    re.MULTILINE,
)

# class_type substrings that own a 'positive' conditioning input.
_SAMPLER_HINTS = ("KSampler", "SamplerCustom", "CFGGuider", "BasicGuider",
                  "SamplerCustomAdvanced")

# Nodes that pass conditioning through; we recurse into these inputs.
_COND_PASSTHROUGH_INPUTS = (
    "conditioning", "conditioning_1", "conditioning_to", "conditioning_from",
    "positive", "cond", "base_conditioning",
)

# Widget/input names that hold the actual prompt string.
_TEXT_INPUTS = ("text", "text_g", "text_l", "prompt", "string", "value",
                "populated_text", "wildcard_text")

# A1111-style network tags: <lora:name:1>, <lyco:name:0.8:0.5>, <hypernet:x:1>.
# The weight part is free-form (several numbers, or none at all), so anything
# that is not an angle bracket is accepted up to the closing '>'.
_NETWORK_TAG = re.compile(
    r"<\s*(?:lora|loras|lyco|lycoris|hypernet|hypernetwork)\s*:[^<>]*>",
    re.IGNORECASE,
)

ON_FAILURE_MODES = ["empty string", "error message"]


# --------------------------------------------------------------- raw metadata
def read_raw_metadata(path: str) -> dict:
    """Return every text-ish metadata field found in the image file."""
    from PIL import Image

    out = {}
    with Image.open(path) as im:
        # PNG text chunks (and anything else PIL exposes as .info strings)
        for k, v in (im.info or {}).items():
            if isinstance(v, str) and v.strip():
                out[k] = v

        # EXIF UserComment (JPEG / WEBP) - this is where Civitai puts it
        try:
            exif = im.getexif()
            ifd = exif.get_ifd(0x8769)  # Exif IFD
            uc = ifd.get(0x9286)        # UserComment
            if uc:
                txt = _decode_user_comment(uc)
                if txt:
                    out.setdefault("parameters", txt)
                    out["UserComment"] = txt
            desc = exif.get(0x010E)     # ImageDescription
            if isinstance(desc, str) and desc.strip():
                out.setdefault("ImageDescription", desc)
        except Exception:
            pass
    return out


def _decode_user_comment(raw) -> str:
    """Decode an EXIF UserComment blob (8-byte charset header + payload)."""
    if isinstance(raw, str):
        return raw
    if not isinstance(raw, bytes):
        return ""
    head, body = raw[:8], raw[8:]
    if head.startswith(b"UNICODE"):
        # Spec says UCS-2; endianness varies by writer, so try both and keep
        # whichever yields fewer replacement characters.
        best, best_bad = "", None
        for enc in ("utf-16-be", "utf-16-le"):
            try:
                s = body.decode(enc, errors="replace")
            except Exception:
                continue
            bad = s.count("�")
            if best_bad is None or bad < best_bad:
                best, best_bad = s, bad
        return best.rstrip("\x00")
    if head.startswith(b"ASCII"):
        return body.decode("ascii", errors="replace").rstrip("\x00")
    for enc in ("utf-8", "utf-16-be", "latin-1"):
        try:
            return raw.decode(enc).rstrip("\x00")
        except Exception:
            continue
    return ""


# ------------------------------------------------------------- A1111 / Civitai
def parse_a1111(block: str):
    """Split an A1111/Civitai parameters block into (positive, negative).

    Layout is: positive prompt, optional 'Negative prompt:' section, then a
    trailing settings line. Both prompts may span several lines.
    """
    if not block or not block.strip():
        return "", ""
    text = block.replace("\r\n", "\n")

    neg = ""
    idx = text.find("Negative prompt:")
    if idx != -1:
        pos = text[:idx]
        rest = text[idx + len("Negative prompt:"):]
        m = _A1111_PARAM_LINE.search(rest)
        neg = (rest[:m.start()] if m else rest).strip()
    else:
        m = _A1111_PARAM_LINE.search(text)
        pos = text[:m.start()] if m else text

    return pos.strip(), neg.strip()


def _looks_like_a1111(block: str) -> bool:
    return bool(block) and bool(_A1111_PARAM_LINE.search(block))


# ------------------------------------------------------- Civitai extraMetadata
def parse_civitai_extra(workflow_json: str):
    """Civitai stores explicit prompts in an 'extraMetadata' blob.

    It sits under workflow['extra']['extraMetadata'] in PNG workflow chunks,
    but at the top level in the JSON graph Civitai writes to EXIF, so both
    locations are checked.
    """
    try:
        wf = json.loads(workflow_json)
    except Exception:
        return None
    if not isinstance(wf, dict):
        return None
    extra = wf.get("extraMetadata") or (wf.get("extra") or {}).get("extraMetadata")
    if not extra:
        return None
    if isinstance(extra, str):
        try:
            extra = json.loads(extra)
        except Exception:
            return None
    if not isinstance(extra, dict):
        return None
    pos = extra.get("prompt") or ""
    neg = extra.get("negativePrompt") or extra.get("negative_prompt") or ""
    if not str(pos).strip():
        return None
    return str(pos).strip(), str(neg).strip()


# ----------------------------------------------------------- ComfyUI API graph
def _resolve_text(api: dict, node_id, seen=None):
    """Walk the graph from a conditioning link and return its prompt text."""
    if seen is None:
        seen = set()
    key = str(node_id)
    if key in seen or key not in api:
        return ""
    seen.add(key)

    node = api[key]
    inputs = node.get("inputs", {}) or {}

    # Direct text widget on this node (CLIPTextEncode and friends).
    for name in _TEXT_INPUTS:
        if name in inputs:
            val = inputs[name]
            if isinstance(val, str) and val.strip():
                return val.strip()
            # The widget is itself wired to another node (primitive, concat...).
            if isinstance(val, list) and val:
                got = _resolve_text(api, val[0], seen)
                if got:
                    return got

    # Conditioning passthrough (ControlNet, ConditioningCombine, LoRA hooks...).
    for name in _COND_PASSTHROUGH_INPUTS:
        val = inputs.get(name)
        if isinstance(val, list) and val:
            got = _resolve_text(api, val[0], seen)
            if got:
                return got

    # Last resort: any linked input at all.
    for val in inputs.values():
        if isinstance(val, list) and val and isinstance(val[0], (str, int)):
            got = _resolve_text(api, val[0], seen)
            if got:
                return got
    return ""


def parse_comfy_api(prompt_json: str):
    """Extract (positive, negative) from a ComfyUI API-format prompt graph.

    The positive prompt is found by following the sampler's 'positive' link,
    which is the only reliable way to tell it apart from the negative one -
    picking "the first CLIPTextEncode" often lands on the negative.
    """
    try:
        api = json.loads(prompt_json)
    except Exception:
        return None
    if not isinstance(api, dict):
        return None

    pos = neg = ""
    for _nid, node in api.items():
        if not isinstance(node, dict):
            continue
        ct = str(node.get("class_type", ""))
        if not any(h in ct for h in _SAMPLER_HINTS):
            continue
        inputs = node.get("inputs", {}) or {}
        p, n = inputs.get("positive"), inputs.get("negative")
        if isinstance(p, list) and p and not pos:
            pos = _resolve_text(api, p[0])
        if isinstance(n, list) and n and not neg:
            neg = _resolve_text(api, n[0])
        if pos:
            break

    # No sampler found (or nothing wired): fall back to any text encoder.
    if not pos:
        for _nid, node in api.items():
            if not isinstance(node, dict):
                continue
            if "CLIPTextEncode" in str(node.get("class_type", "")):
                t = (node.get("inputs", {}) or {}).get("text")
                if isinstance(t, str) and t.strip():
                    pos = t.strip()
                    break

    if not pos and not neg:
        return None
    return pos, neg


def parse_comfy_workflow(workflow_json: str):
    """Fallback for the UI-format graph: read CLIPTextEncode widget values.

    Used only when the API graph is missing. Node titles are the sole hint
    about which one is negative, so this is best-effort by design.
    """
    try:
        wf = json.loads(workflow_json)
    except Exception:
        return None
    nodes = wf.get("nodes") if isinstance(wf, dict) else None
    if not isinstance(nodes, list):
        return None

    texts = []
    for n in nodes:
        if not isinstance(n, dict) or "CLIPTextEncode" not in str(n.get("type", "")):
            continue
        vals = [v for v in (n.get("widgets_values") or []) if isinstance(v, str)]
        if not vals:
            continue
        title = str(n.get("title", "")).lower()
        texts.append((title, vals[0].strip()))
    if not texts:
        return None

    pos = neg = ""
    for title, txt in texts:
        if "neg" in title and not neg:
            neg = txt
        elif not pos and "neg" not in title:
            pos = txt
    if not pos:
        pos = texts[0][1]
    return pos, neg


# --------------------------------------------------------------- LoRA stripping
def remove_network_tags(text: str) -> str:
    """Drop <lora:...> / <lyco:...> / <hypernet:...> tags from a prompt.

    Removing a tag leaves punctuation behind ("1girl, <lora:x:1>, solo" would
    become "1girl, , solo"), so the separators the removal orphaned are cleaned
    up too. Formatting that had nothing to do with a tag is left alone.
    """
    if not text:
        return text
    if not _NETWORK_TAG.search(text):
        return text

    # A tag sitting alone on its line takes the whole line with it, otherwise
    # the removal would leave a blank line behind. Done first and anchored to
    # full lines, so paragraph breaks elsewhere in the prompt are preserved.
    out = re.sub(
        r"(?m)^[^\S\n]*(?:%s[^\S\n]*,?[^\S\n]*)+$\n?" % _NETWORK_TAG.pattern,
        "", text, flags=re.IGNORECASE)

    out = _NETWORK_TAG.sub("", out)                     # remaining inline tags
    out = re.sub(r"[^\S\n]{2,}", " ", out)              # runs of spaces/tabs
    out = re.sub(r",(?:[^\S\n]*,)+", ",", out)          # ", ,"      -> ","
    out = re.sub(r"(?m)^[^\S\n]*,[^\S\n]*$", "", out)   # comma-only line
    out = re.sub(r"(?m)^[^\S\n]*,[^\S\n]*", "", out)    # comma opening a line
    out = re.sub(r"\n{3,}", "\n\n", out)                # blank-line pile-up
    return out.strip().strip(",").strip()


# ------------------------------------------------------------------ public API
def extract_prompts(path: str):
    """Return (positive, negative, source_label, raw_metadata_text).

    Sources are tried most-explicit first, so a Civitai image that carries both
    its own metadata and a ComfyUI graph reports the Civitai prompt.
    """
    meta = read_raw_metadata(path)
    if not meta:
        return "", "", "none", ""

    raw_dump = "\n\n".join("### %s\n%s" % (k, v) for k, v in meta.items())

    # Civitai writes its graph to EXIF, ComfyUI to the 'prompt'/'workflow'
    # chunks - so any field may hold JSON. Collect them all rather than
    # assuming a fixed key.
    json_blocks = [v for v in meta.values() if v.lstrip()[:1] in "{["]

    # 1) Civitai's explicit blob - the only source that labels the prompts.
    for block in json_blocks:
        got = parse_civitai_extra(block)
        if got:
            return got[0], got[1], "civitai extraMetadata", raw_dump

    # 2) A1111 / Civitai parameters block (PNG chunk or EXIF UserComment).
    for key in ("parameters", "UserComment", "Description", "ImageDescription",
                "comment", "Comment"):
        block = meta.get(key)
        if _looks_like_a1111(block):
            pos, neg = parse_a1111(block)
            if pos or neg:
                return pos, neg, "a1111 (%s)" % key, raw_dump

    # 3) ComfyUI API graph, followed from the sampler's positive link.
    for block in json_blocks:
        got = parse_comfy_api(block)
        if got:
            return got[0], got[1], "comfyui prompt graph", raw_dump

    # 4) ComfyUI UI graph (widget values only).
    for block in json_blocks:
        got = parse_comfy_workflow(block)
        if got:
            return got[0], got[1], "comfyui workflow graph", raw_dump

    # 5) Nothing structured: a bare text field may still be the prompt itself.
    #    JSON is excluded here - dumping a raw graph as a "prompt" is worse
    #    than reporting that nothing was found.
    for key in ("parameters", "UserComment", "Description"):
        block = meta.get(key, "").strip()
        if block and block[:1] not in "{[":
            return block, "", "raw %s" % key, raw_dump

    return "", "", "unrecognized", raw_dump


# ----------------------------------------------------------------- ComfyUI node
def _input_dir():
    import folder_paths
    return folder_paths.get_input_directory()


def _resolve_image_path(image: str, image_path: str = "") -> str:
    """Turn the widget value into a real path.

    The upload button and clipspace hand over annotated names such as
    'clipspace/x.png [input]', which only folder_paths knows how to resolve,
    so that is tried first and plain joining is just the fallback.
    """
    if image_path and image_path.strip():
        return os.path.expanduser(image_path.strip())
    name = (image or "").strip()
    if not name:
        return ""
    try:
        import folder_paths
        return folder_paths.get_annotated_filepath(name)
    except Exception:
        return os.path.join(_input_dir(), name)


class CivitaiPromptLoader:
    """Load an image AND recover the prompt stored in its metadata."""

    CATEGORY = "LLM Prompt Studio"
    FUNCTION = "load"
    RETURN_TYPES = ("IMAGE", "MASK", "STRING", "STRING", "STRING")
    RETURN_NAMES = ("image", "mask", "positive", "negative", "raw_metadata")

    @classmethod
    def INPUT_TYPES(cls):
        try:
            d = _input_dir()
            files = sorted(
                f for f in os.listdir(d)
                if os.path.isfile(os.path.join(d, f))
                and f.lower().endswith((".png", ".jpg", ".jpeg", ".webp"))
            )
        except Exception:
            files = []
        # Everything lives in "required", the way ComfyUI's own LoadImageMask
        # does it - widget values are serialized positionally, so a mix of
        # required and optional widgets can shift them in saved workflows.
        return {
            "required": {
                "image": (files, {"image_upload": True,
                    "tooltip": "Image to load. Its embedded metadata is parsed "
                               "to recover the prompt it was generated with."}),
                "image_path": ("STRING", {"default": "",
                    "tooltip": "Optional absolute path, overrides the dropdown. "
                               "Use it to read an image outside ComfyUI's input "
                               "folder."}),
                "strip_lora_tags": ("BOOLEAN", {"default": True,
                    "tooltip": "Remove LoRA/LyCORIS/hypernet tags from the "
                               "outputs, e.g. <lora:Train_Entrance_SDXL:1>. "
                               "The commas they leave behind are cleaned up "
                               "too. Turn off to keep the prompt verbatim."}),
                "on_failure": (ON_FAILURE_MODES, {
                    "default": ON_FAILURE_MODES[0],
                    "tooltip": "What 'positive' returns when no prompt is found: "
                               "an empty string, or a short diagnostic message."}),
            },
        }

    @classmethod
    def VALIDATE_INPUTS(cls, **kwargs):
        """Accept whatever the graph sends and normalise it in load().

        A workflow saved with an older version of this node has its widget
        values shifted by one, which would otherwise abort the whole prompt
        with 'Value not in list'. Degrading to defaults beats refusing to run.
        """
        return True

    @classmethod
    def IS_CHANGED(cls, image, image_path="", **kwargs):
        path = _resolve_image_path(image, image_path)
        try:
            st = os.stat(path)
            return "%s:%s" % (st.st_mtime_ns, st.st_size)
        except Exception:
            return float("nan")

    def load(self, image, image_path="", strip_lora_tags=True,
             on_failure=None):
        import numpy as np
        import torch
        from PIL import Image, ImageOps

        # VALIDATE_INPUTS lets anything through, so coerce here. Values can be
        # off by one when an older workflow is reloaded; falling back to the
        # defaults keeps the graph running instead of failing it.
        if on_failure not in ON_FAILURE_MODES:
            on_failure = ON_FAILURE_MODES[0]
        if not isinstance(strip_lora_tags, bool):
            strip_lora_tags = str(strip_lora_tags).strip().lower() in (
                "true", "1", "yes", "on")
        if not isinstance(image_path, str):
            image_path = ""
        if not isinstance(image, str):
            image = ""

        path = _resolve_image_path(image, image_path)

        if not os.path.isfile(path):
            msg = "[CivitaiPromptLoader] file not found: %s" % path
            print(msg)
            empty = torch.zeros((1, 64, 64, 3), dtype=torch.float32)
            return (empty, torch.zeros((1, 64, 64), dtype=torch.float32),
                    msg, "", "")

        # --- metadata first (must read the FILE, a tensor has none) ---
        try:
            positive, negative, source, raw = extract_prompts(path)
        except Exception as e:
            positive, negative, source, raw = "", "", "error: %s" % e, ""
            print("[CivitaiPromptLoader] metadata parse failed:", e)

        if strip_lora_tags:
            n_tags = len(_NETWORK_TAG.findall(positive)) + \
                     len(_NETWORK_TAG.findall(negative))
            if n_tags:
                positive = remove_network_tags(positive)
                negative = remove_network_tags(negative)
                print("[CivitaiPromptLoader] stripped %d LoRA/network tag(s)"
                      % n_tags)

        if positive:
            print("[CivitaiPromptLoader] prompt found via %s (%d chars)"
                  % (source, len(positive)))
        else:
            print("[CivitaiPromptLoader] no prompt found (%s) in %s"
                  % (source, os.path.basename(path)))
            if on_failure == "error message":
                positive = "[no prompt metadata found - source: %s]" % source

        # --- pixels ---
        pil = Image.open(path)
        pil = ImageOps.exif_transpose(pil)

        if "A" in pil.getbands():
            alpha = np.asarray(pil.getchannel("A"), dtype=np.float32) / 255.0
            mask = torch.from_numpy(1.0 - alpha).unsqueeze(0)
        else:
            mask = torch.zeros((1, pil.height, pil.width), dtype=torch.float32)

        arr = np.asarray(pil.convert("RGB"), dtype=np.float32) / 255.0
        tensor = torch.from_numpy(arr).unsqueeze(0)

        return (tensor, mask, positive, negative, raw)


NODE_CLASS_MAPPINGS = {"CivitaiPromptLoader": CivitaiPromptLoader}
NODE_DISPLAY_NAME_MAPPINGS = {"CivitaiPromptLoader": "Load Image + Prompt (Civitai/A1111/ComfyUI)"}
